---
- name: Enable dnf php module
  ansible.builtin.command: '{{ item }}'
  changed_when: false
  loop:
    - dnf module reset php -y
    - "dnf module enable {{ remi_repo }} -y"

- name: Install PHP and the packages
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ php_packages }}'

- name: Set PHP timezone to Asia/Tokyo
  community.general.ini_file:
    dest: /etc/php.ini
    section: Date
    option: date.timezone
    value: "Asia/Tokyo"
    mode: 0755
