---
- name: Install PHP
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
    enablerepo: '{{ remi_repo }}'
  loop: '{{ php_packages }}'

- name: Set timezone to Asia/Tokyo
  community.general.ini_file:
    dest: /etc/php.ini
    section: Date
    option: date.timezone
    value: "Asia/Tokyo"
    mode: 0755
