---
- name: "Install PHP with remi: {{ remi_repo }}"
  ansible.builtin.package:
    name:
      - php
      - php-gd
      - php-gmp
      - php-intl
      - php-ldap
      - php-mbstring
      - php-mcrypt
      - php-mysqlnd
      - php-opcache
      - php-pdo
      - php-pear
      - php-pear-Net-Curl
      - php-pecl-apcu-bc
      - php-pecl-redis
      - php-pecl-zip
      - php-soap
      - php-xml
    state: present
    enablerepo: '{{ remi_repo }}'

- name: Set timezone to Asia/Tokyo
  community.general.ini_file:
    dest: /etc/php.ini
    section: Date
    option: date.timezone
    value: "Asia/Tokyo"
    mode: 0755
