---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether PHP installed
      ansible.builtin.command: php -v
      register: php_installed
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Make sure PHP is installed
      ansible.builtin.debug:
        var: php_installed

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
